<#
.SYNOPSIS
    Build script to create a bundled version of repo-nav for distribution.

.DESCRIPTION
    This script concatenates all PowerShell source files into a single
    'repo-nav-bundle.ps1' file, eliminating the overhead of loading 73+
    individual files at startup.

    The bundle preserves the exact dependency order and produces a
    functionally identical script that loads 4-5x faster.

.EXAMPLE
    .\Build-Bundle.ps1
    Creates repo-nav-bundle.ps1 in the same directory

.EXAMPLE
    .\Build-Bundle.ps1 -OutputPath "C:\dist\repo-nav.ps1"
    Creates the bundle at a custom location

.NOTES
    Run this script after any code changes to regenerate the bundle.
    The original source files remain untouched.
#>

param(
    [string]$OutputPath = (Join-Path $PSScriptRoot "repo-nav-bundle.ps1"),
    [switch]$Minify
)

$ErrorActionPreference = 'Stop'
$scriptRoot = $PSScriptRoot
$srcPath = Join-Path $scriptRoot "src"

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  REPO-NAV BUNDLE BUILDER" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Define the exact load order (matches repo-nav.ps1 import order)
$loadOrder = @(
    # Layer 1: Config
    "Config\Constants.ps1",
    "Config\ColorPalette.ps1",
    
    # Layer 2: Models
    "Models\GitStatusModel.ps1",
    "Models\AliasInfo.ps1",
    "Models\RepositoryModel.ps1",
    "Models\IntegrationFlowModel.ps1",
    "Core\Common\OperationResult.ps1",
    
    # Layer 3: Core Infrastructure
    "Core\Interfaces\IProgressReporter.ps1",
    "Services\WindowSizeCalculator.ps1",
    "Core\State\NavigationState.ps1",
    
    # Layer 4: Services
    "Services\ConfigurationService.ps1",
    "Services\UserPreferencesService.ps1",
    "Services\LocalizationService.ps1",
    "Services\AliasManager.ps1",
    "Services\GitReadService.ps1",
    "Services\GitWriteService.ps1",
    "Services\GitService.ps1",
    "Services\NpmService.ps1",
    "Services\ParallelGitLoader.ps1",
    "Services\RepositoryOperationsService.ps1",
    "Services\FavoriteService.ps1",
    "Services\SearchService.ps1",
    "Services\RenderOrchestrator.ps1",
    "Services\LoggerService.ps1",
    
    # Layer 5: UI Base & Framework
    "UI\Base\ConsoleHelper.ps1",
    "UI\Framework\ConsoleView.ps1",
    
    # Layer 6: UI Components
    "UI\ViewModels\RepositoryViewModel.ps1",
    "UI\UIRenderer.ps1",
    "UI\Components\ProgressIndicator.ps1",
    "UI\Components\ColorSelector.ps1",
    "UI\Components\OptionSelector.ps1",
    "UI\Renderers\FilteredListRenderer.ps1",
    "UI\Renderers\IntegrationFlowRenderer.ps1",
    "UI\Components\FilteredListSelector.ps1",
    "UI\Dashboards\IntegrationFlowDashboard.ps1",
    "UI\Services\ConsoleProgressReporter.ps1",
    
    # Layer 7: Core Managers
    "Core\Services\GitStatusManager.ps1",
    "Core\Services\RepositorySorter.ps1",
    "Core\RepositoryManager.ps1",
    
    # Layer 8: UI Controllers & Views
    "UI\Controllers\PreferencesMenuController.ps1",
    "UI\Views\RepositoryManagementView.ps1",
    "UI\Views\AliasView.ps1",
    "UI\Views\SearchView.ps1",
    
    # Layer 9: Commands
    "Core\State\CommandContext.ps1",
    "Core\Commands\INavigationCommand.ps1",
    "Core\Commands\ExitCommand.ps1",
    "Core\Commands\NavigationCommand.ps1",
    "Core\Commands\RepositoryCommand.ps1",
    "Core\Commands\GitCommand.ps1",
    "Core\Commands\FavoriteCommand.ps1",
    "Core\Commands\AliasCommand.ps1",
    "Core\Commands\NpmCommand.ps1",
    "Core\Commands\RepositoryManagementCommand.ps1",
    "Core\Commands\PreferencesCommand.ps1",
    "Core\Commands\CreateFolderCommand.ps1",
    "Core\Commands\SearchCommand.ps1",
    
    # Layer 10: Flows
    "Core\Flows\FlowControllerBase.ps1",
    "Core\Flows\IntegrationFlowController.ps1",
    "Core\Flows\QuickChangeFlowController.ps1",
    "Core\Flows\GitFlowCommand.ps1",
    
    # Layer 11: Engine
    "Core\Engine\CommandFactory.ps1",
    "Core\Engine\InputHandler.ps1",
    "Core\Engine\NavigationLoop.ps1",
    
    # Layer 12: Startup
    "Startup\ServiceRegistry.ps1",
    "App\AppBuilder.ps1"
)

# Build the bundle content
$bundleContent = [System.Text.StringBuilder]::new()

# Add header
$header = @"
<#
.SYNOPSIS
    repo-nav Bundle - Single-file distribution version
    
.DESCRIPTION
    This is an auto-generated bundle of repo-nav.
    DO NOT EDIT THIS FILE DIRECTLY - edit the source files and rebuild.
    
    Generated: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
    Source files: $($loadOrder.Count)
    
.NOTES
    To regenerate this bundle, run: .\Build-Bundle.ps1
#>

param(
    [Parameter(Mandatory=`$false)]
    [string]`$BasePath
)

`$scriptRoot = `$PSScriptRoot

"@

[void]$bundleContent.AppendLine($header)

# Process each file
$processedCount = 0
$totalSize = 0

foreach ($relativePath in $loadOrder) {
    $fullPath = Join-Path $srcPath $relativePath
    
    if (-not (Test-Path $fullPath)) {
        Write-Host "  [WARN] Missing: $relativePath" -ForegroundColor Yellow
        continue
    }
    
    $fileContent = Get-Content $fullPath -Raw -Encoding UTF8
    $fileSize = (Get-Item $fullPath).Length
    $totalSize += $fileSize
    
    # Add section marker
    [void]$bundleContent.AppendLine("#region $relativePath")
    [void]$bundleContent.AppendLine("# Source: $relativePath")
    
    if ($Minify) {
        # Remove comment-only lines and empty lines (basic minification)
        $lines = $fileContent -split "`n" | Where-Object { 
            $trimmed = $_.Trim()
            $trimmed -ne '' -and -not ($trimmed -match '^#(?!\>)') -and -not ($trimmed -match '^<#')
        }
        $fileContent = $lines -join "`n"
    }
    
    [void]$bundleContent.AppendLine($fileContent)
    [void]$bundleContent.AppendLine("#endregion")
    [void]$bundleContent.AppendLine("")
    
    $processedCount++
    $pct = [int](($processedCount / $loadOrder.Count) * 100)
    Write-Host "`r  Processing: $pct% ($processedCount/$($loadOrder.Count))" -NoNewline
}

Write-Host ""

# Add initialization code (from original repo-nav.ps1)
$footer = @"

#region Initialization
# Initialize Constants
[Constants]::Initialize(`$scriptRoot)
#endregion

#region Main Entry Point
function Start-RepositoryNavigator {
    param(
        [string]`$BasePath = (Split-Path -Parent `$PSScriptRoot)
    )
    
    try {
        `$appContext = [AppBuilder]::Build(`$BasePath)
        Start-NavigationLoop -Context `$appContext
    }
    catch {
        Write-Host ""
        Write-Host "Error starting repository navigator:" -ForegroundColor Red
        Write-Host `$_.Exception.Message -ForegroundColor Red
        Write-Host ""
        Write-Host "Stack trace:" -ForegroundColor DarkGray
        Write-Host `$_.ScriptStackTrace -ForegroundColor DarkGray
        Write-Host ""
        Write-Host "Press any key to exit..." -ForegroundColor Gray
        `$null = `$Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
    }
}
#endregion

#region Execute
if (`$MyInvocation.InvocationName -ne '.') {
    if (-not `$BasePath) {
        `$BasePath = [Constants]::ReposBasePath
    }
    Start-RepositoryNavigator -BasePath `$BasePath
}
#endregion
"@

[void]$bundleContent.AppendLine($footer)

# Write the bundle
$bundleContent.ToString() | Set-Content -Path $OutputPath -Encoding UTF8 -Force

$outputSize = (Get-Item $OutputPath).Length / 1KB

Write-Host ""
Write-Host "  Bundle created successfully!" -ForegroundColor Green
Write-Host ""
Write-Host "  Output: $OutputPath" -ForegroundColor White
Write-Host "  Files bundled: $processedCount" -ForegroundColor White
Write-Host "  Bundle size: $([Math]::Round($outputSize, 2)) KB" -ForegroundColor White
Write-Host ""
Write-Host "  To use: .\repo-nav-bundle.ps1" -ForegroundColor Cyan
Write-Host ""
